Release madgui 19.3.2
- fix TypeError: set_draggable() missing 1 required positional argument
  (in shared plot mode)
- add units in curve y labels
- change some quantity labels
- separate function to edit model parameters, for use in plugins etc